# Generated by Django 3.2.5 on 2021-08-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='return',
            options={'ordering': ('-created_date',)},
        ),
        migrations.RenameField(
            model_name='return',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='wallet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
