# Generated by Django 3.2.5 on 2021-08-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_purchase_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='return_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
