# Generated by Django 3.2.5 on 2021-08-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210816_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='return',
            options={'ordering': ['-created_date']},
        ),
    ]
