# Generated by Django 3.2.5 on 2021-08-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_return_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='return',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='return',
            old_name='created_date',
            new_name='created',
        ),
    ]
